/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc.algo;

import org.junit.Test;
import static org.junit.Assert.*;

public class RunnerTest {
    @Test public void appHasAGreeting() {
    	Runner runner = new Runner();
        assertNotNull("null", runner);
    }
}
